name: Make Resume

on: [push]

jobs:
  test-action:
    runs-on: ubuntu-20.04
    container: lironavon/docker-puppeteer-container:14.16.0
    steps:
      - uses: actions/checkout@v3
   #   - uses: browser-actions/setup-chrome@v1.2.0
      - name: make-resume
        uses:  ./resume-action
        with:
          github_user_name: ${{ github.repository_owner }}
      - name: push resume to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
