name: Resume 
on: [push]

jobs:
#   test:
    # runs-on: ubuntu-latest

    # steps:
    #   - uses: actions/checkout@v3
    #   - uses: actions/setup-node@v3
    #     with:
    #       cache: yarn
    #       node-version: 16
    #   - run: yarn install --frozen-lockfile

  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - run: cd resume-action && yarn install --frozen-lockfile

      - name: make-resume
        id: make-resume
        uses: ./resume-action
        with:
          github_user_name: NeonGamerBot-QK
      - name: push resume to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
            target_branch: output-resume
            build_dir: dist
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #- name: ensure the generated file exists
     #   run: |
      #    ls dist
     #     test -f dist/file.pdf
          
    #   - uses: crazy-max/ghaction-github-pages@v3.1.0
    #     with:
    #       target_branch: output
    #       build_dir: dist
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
#   deploy-ghpages:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           cache: yarn
#           node-version: 16
#       - run: yarn install --frozen-lockfile

#       - run: yarn build:demo
#         env:
#           GITHUB_USER_CONTRIBUTION_API_ENDPOINT: https://snk-one.vercel.app/api/github-user-contribution/

#       - uses: crazy-max/ghaction-github-pages@v3.1.0
#         if: success() && github.ref == 'refs/heads/main'
#         with:
#           target_branch: gh-pages
#           build_dir: packages/demo/dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN_GH_PAGES }}
