name: Make Resume

on: [push]

jobs:
  test-action:
    runs-on: ubuntu-20.04
    container: lironavon/docker-puppeteer-container:14.16.0
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - run: yarn install --frozen-lockfile
      - name: make-resume
        uses: NeonGamerBot-QK/resume-action@0.0.4v-1
        with:
          github_user_name: ${{ github.repository_owner }}
      - name: push resume to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
