name: Make Resume

on: [push]

jobs:
  ci:
    runs-on: ubuntu-20.04
    container: lironavon/docker-puppeteer-container:14.16.0
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make-resume
        uses: NeonGamerBot-QK/resume-action@v0.0.3-why
        with:
          github_user_name: ${{ github.repository_owner }}
      - name: push resume to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
